#!/usr/bin/env python

import sys

def usage():
    print 'Usage:'
    print '\t' + sys.argv[0] + ' SYMTAB'

if len(sys.argv) != 2:
    usage()
    exit(1)

fpath = sys.argv[1]
f = open(fpath)

print '/* Autogenerated! Do not edit. */\n'

print '#ifndef __ROM_TABLE_H__'
print '#define __ROM_TABLE_H__\n'

lines = f.readlines();
f.close()

for l in lines:
    items = l.split()
    if items[1] == 'T':
        s = '#define' + ' ' + items[1] + '__' + items[2].upper()
        a = '0x' + items[0]
        print ('{0:55s} {1:10s}'.format(s, a))

print '\n#endif /* __ROM_TABLE_H__ */'
